version: '3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: gutendex
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: gutendex
    expose:
      - 5432
    networks:
      - back-end
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gutendex"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  gutendex:
    build: .
    expose:
      - 8000
    networks:
      - front-end
      - back-end
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 20s
      timeout: 10s
      retries: 8
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
  proxy:
    image: nginx:1.23.3-alpine-slim
    ports:
      - 80:80
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/html/static
    networks:
      - front-end
    depends_on:
      gutendex:
        condition: service_healthy


networks:
 front-end:
 back-end:




    

